project:
  type: website
  output-dir: docs

website:
  title: "montanaBats"
  navbar:
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Presentations"
        menu:
          - talks.qmd
          - about.qmd 
      - text: "Predictions"
        file: predictions.qmd
    right:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/javirudolph/montanaBats
          - text: Report a Bug
            url:  https://github.com/javirudolph/montanaBats/issues
  page-footer: 
    left: "Copyright 2022, F. Javiera Rudolph" 
    right: 
      - icon: github
        href: https://github.com/javirudolph
        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



