project:
  type: website
  output-dir: docs

website:
  title: "montanaBats"
  navbar:
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Model"
        menu:
          - model.qmd
          - jurisdictions.qmd
          - covariates.qmd
          - predictions.qmd
          - estimation.qmd
      - text: "More"
        menu:
          - toymodel.qmd
          - old.qmd
    right:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/javirudolph/montanaBats
          - text: Issues
            url:  https://github.com/javirudolph/montanaBats/issues
  page-footer: 
    left: "Copyright 2022, F. Javiera Rudolph" 
    right: 
      - icon: github
        href: https://github.com/javirudolph
        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



