project:
  type: website
  output-dir: docs

website:
  title: "montanaBats"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/javirudolph/montanaBats
          - text: Report a Bug
            url:  https://github.com/javirudolph/montanaBats/issues

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



