---
title: "Management Strategies - Alternatives"
---

# Attack WNS

## Reduce *Pd* growth

-   Chemical and mechanical treatment of known hibernaculums
    -   (e.g., Chitosan applied to bats, UV, PEG - apply to surface)
    -   Treatable caves: Azure, Mystery, Little Ice
-   Maintain optimal microhabitat in hibernacula
-   Apply probiotics on bats in the hibernaculum
-   Apply probiotics on ats in the bat houses and in the landscape

## Increase Pd tolerance in bats

-   Improve quality of water sources near roosts
    -   (e.g., increase access, structural integrity of stock tanks, bat friendly, availability of water for entire season)
-   Release pheromones for insect lures to provide efficient foraging opportunities
-   Insect lures before fall swarming to provide efficient foraging opportunities
-   Insect lures during spring to provide efficient foraging opportunities
-   Increase water availability near hibernacula to prevent distress from WNS induced dehydration
-   Increase foraging opportunities through habitat management near hibernacula to prevent distress from WNS induced dehydration
-   Vaccinate bats in hibernacula
-   Vaccinate bats in bat houses and landscape

## Transmission reduction

-   Minimize research capture of bats during late summer and fall to reduce interstate and intrastate transmission
-   Restrict human access to bat caves

# General population management {.smaller}

## Maintain health of riparian forests

-   Increase age and stand diversity
-   Remove invasive like Russian olives, Tamarisk
-   Increase recruitment of cottonwood (excellent roost trees) trees by allowing flooding, promoting natural and established artificial dams
-   Promote regeneration of riparian forests by fencing
-   Promote regeneration of riparian forests by livestock management

## Water sources

-   Provide consistent water sources during dry season in known dry areas through following actions based on location:
    -   Increase stock reservoirs
    -   Promote beaver dams through relocation
    -   Bat friendly stock tanks
    -   Retrofit wildlife friendly bat ramps in stock tanks

## Increase forest diversity

-   Maintain snags\> 20 inches in diameter
-   Restrict logging between May-July to prevent maternity roosts disturbance
-   Encourage stand diversity (age and habitat type) by following ways:
-   Encourage young seral stages in public lands
-   Encourage young seral stages in private lands (family forest program USDA)
-   Design projects to promote large trees and old growth forests
-   Encourage forest thinning and understory removal by promoting multiple benefits (prevent fire fuel, insect outbreaks etc) - Restore native habitat in burnt forested regions within a reasonable timeframe

## Talus and rocky outcrop management

-   Prevent destruction of talus and rocky-outcrop from anthropogenic development

# Improve reproductive outcomes 

## Protection of aggregation of bats in maternity season 

-   Insect lures before fall swarming  to provide efficient foraging opportunities 
-   Insect lures during spring  to provide efficient foraging opportunities 
-   Microclimate controlled bat boxes available in spring 
-   Change project timing around maternity colonies to prevent disturbance 
-   Outreach against maternity colony destructions  
-   Funding program for rehousing maternity colonies (building bat boxes etc) 
-   Encourage Montana Wildlife Control operators to take NWCOA bat standard certification  
-   Maintain and upkeep known  maternity roosts (unused buildings/mines etc) 
-   Outreach to MDT against destruction of maternity colony under bridges  
-   State, federal, and tribal governments should use no net loss approach for agency buildings by putting alternate roosts 


# Management in landscape
## Citizen related 

-   Active provisions of alternative roosting sites in important areas through following ways:  
    -   Microclimate controlled bat boxes 
    -   Larger bat boxes to allow for a range of temperature 
    -   Guide citizens about location and type of the bat boxes 
-   Maintain and create (when needed) bat access in caves and mines through structural reinforcement 




