---
title: "Estimation"
execute: 
  echo: false
html:
    code-fold: true
    code-summary: "Show the code"
---

We fitted a series of multistate multiscale occupancy models to bat call data provided by the state of Montana. The data provided was not species-specific but was associated to a frequency of bat calls known to be susceptible to white nose syndrome. These models allowed us to evaluate the impact of environmental covariates on the likelihood of bat occupancy at multiple abundance levels. In this context, multistate refers to three levels of bat activity: no bats, few bats, and many bats. On the other hand, multiscale refers to the fact that each grid cell that was sampled had multiple sites sampled over a certain number of nights.

The multistate aspect of the models allows us to understand not just if bats are present, but also how many bats are present, without fitting an abundance model. We were able to consider several variables that might affect the likelihood of bat occupancy, such as temperature, humidity, forest cover, and elevation, following the regional model published by NABat.

Overall, our analysis using these multistate multiscale occupancy models has allowed us to gain a base understanding of the factors affecting bat occupancy in Montana, which we can use to generate base predictive models that incorporate different management strategies that support and protect bat populations in the state.

# Model descriptions 

We fitted three different models: a null model with no covariates to serve as a base comparison, a model with covariates affecting occupancy states only, and a third model with covariates affecting occupancy and detection. Mathematical descriptions for the three models are found below and the code used to fit these models is in the following [script](https://github.com/javirudolph/montanaBats/blob/main/scripts/estimation_singleseasonMSMS_batcall_dat.R). Data is not provided but can be requested through the state of Montana library.

## Null multi-state multi-scale model 

A grid cell $i$ is in one of the three states described (1 = no bats, 2 = few bats, 3 = many bats) given:

$$
z_i \sim \text{Categorical}(\Omega)
$$
where the vector of probabilities for each state follows: 

$$
\Omega = [1-\psi \quad \psi(1-r) \quad \psi r]
$$

where $\psi$ is the probability that a grid cell is occupied by bats, and **if** occupied, $r$ is the probability that it will be occupied by *many bats*. In this null model we assume that these probabilities are the same across all grid cells, with no influence of covariates.  

We incorporate the multi-scale component into this model by considering local availability as follows:

$$
a_{i,j} \sim \text{Categorical}[\Theta]
$$
The matrix $\Theta$ gives the probabilities of bats being locally available in each site given their occupancy at the grid cell level. The matrix of probabilities is described as follows, where each row in the matrix is the true state of the grid, and the columns represent the local availability for a site within the grid: 

$$
\Theta = \begin{bmatrix}
         1 & 0 & 0 \\
         1-\theta_2 & \theta_2 & 0 \\
         \theta_{31} & \theta_{32} & \theta_{33}
         \end{bmatrix}
$$
And the detection model follows for each one of the $k$ surveys on each site $j$ within a grid cell $i$: 

$$
y_{i,j,k} \sim \text{Categorical}(detP)
$$

Where $detP$ is given by the matrix below. Each row is the true local availability for a site $j$, and the columns correspond to the observed state in each site during a survey: 


$$
detP = \begin{bmatrix}
         1 & 0 & 0 \\
         1-p_2 & p_2 & 0 \\
         p_{31} & p_{32} & p_{33}
         \end{bmatrix}
$$


## M1 

We incorporate covariates at the cell level but local availability and detection remain as in the null model.

$$
\Omega_i = [1-\psi \quad \psi(1-r) \quad \psi r]_i
$$

the probability of occupancy for site $i$, $\psi_i$ is set as: 

$$
\begin{align*}
logit(\psi_i) = \beta_0 + \beta_1 \cdot \text{Elevation} + \beta_2 \cdot \text{Elevation}^2 +
\beta_3 \cdot \text{Temp} + \beta_4 \cdot \text{Temp}^2 + \\
\beta_5 \cdot \text{Physiographic diversity} +
\beta_6 \cdot \text{Precipitation} + \\
\beta_7 \cdot \text{Percent Forest} + \beta_8 \cdot \text{Percent Wetlands}
\end{align*}
$$

What we think could influence whether there are only a few or many bats could be related to caves (karst), percent forest, and ruggedness (physiographic diversity), thus the probability of a grid cell having *many bats* ($r$) is given by:

$$
logit(r_i) = \beta_0 + \beta_1 \cdot \text{karst} + \beta_2 \cdot \text{Percent Forest} + 
                \beta_3 \cdot \text{Physiographic diversity}
$$

both parameters have region-specific intercepts.  


## M2 

In this third model, we build from M1, and now incorporate site level covariates which include the starting date for the sampling, the duration of sampling period for the site (number of nights), and the site type.

Then, for each site $j$ within a cell $i$, the probability for local availability depends on the site type, starting date, and duration (number of nights recorded for a given site). 

$$
\Theta_{i,j} = \begin{bmatrix}
         1 & 0 & 0 \\
         1-\theta_2 & \theta_2 & 0 \\
         \theta_{31} & \theta_{32} & \theta_{33}
         \end{bmatrix}_{i,j}
$$

$$
logit(\theta) = \beta_0 + \beta_1 \cdot \text{SiteType} + \beta_2 \cdot \text{date} + 
                \beta_3 \cdot \text{date}^2 + \beta_4 \cdot \text{duration}
$$

# Model outcomes 

Our primary objective in fitting these models was to derive estimates of the influence of various covariates on the occupancy state of grids. By using bat call data and incorporating environmental variables, we were able to identify the factors that influence bat occupancy across Montana and we can now use these to generate predictive models and incorporate management actions.

The estimated effects of these covariates on grid-level occupancy provide valuable information for the decision-making processes related to bat conservation and management. For instance, if our analysis reveals that bat occupancy is positively associated with a specific type of region or temperature range, management actions can be taken to promote those factors in areas where bat populations are at risk.


## Covariates at the grid level 

Plot with the estimates and error bars for each of the variables on each of the parameters to see how they compare across the two models that include them. 






