---
title: "Jurisdictions"
---


```{r libs}
#| message: false

# Libraries
library(tidyverse)
library(sf)
library(jagsUI)
library(scales)

```

```{r load_data}

## COVARIATES --------
mt_covariates <- readRDS("datafiles/mt_covariates.RDS") %>% 
  # Abbreviate jurisdiction names
    mutate(jurisd_abbr = case_when(
    jurisdiction == "Montana Fish, Wildlife, and Parks" ~ "MFWP",
    jurisdiction == "US Bureau of Land Management" ~ "BLM",
    jurisdiction == "US Forest Service" ~ "USFS",
    jurisdiction == "Reservations" ~ "Res",
    jurisdiction == "US Fish and Wildlife Service" ~ "USFWS",
    jurisdiction == "National Park Service" ~ "NPS",
    jurisdiction == "Montana Department of Natural Resources and Conservation" ~ "DNRC"
    ))

grid_geometry <- mt_covariates %>% 
  select(GRTS_ID)
```

```{css, echo=FALSE}
.panel-tabset .nav-item {
  font-size: 12px;
}
```

# Jurisdictions
We overlayed a jurisdiction map from the Montana state library and saw which jurisdictions overlapped with different grid cells. Below you can see the different jurisdictions we have considered. 

```{r jurisd_plots}

# List of jurisdictions for color matching
jurisd_list <- unique(mt_covariates$jurisdiction[!is.na(mt_covariates$jurisdiction)])
jurisd_list_abbr <- unique(mt_covariates$jurisd_abbr[!is.na(mt_covariates$jurisd_abbr)])
n_jurisd <- length(jurisd_list)

# get colors
jurisd_cols <- brewer_pal(palette = "Dark2")(n_jurisd)
names(jurisd_cols) <- jurisd_list_abbr

# all jurisdictions
mt_covariates %>% 
  ggplot() +
  geom_sf(color = "black", aes(fill = jurisd_abbr)) +
  labs(fill = "Jurisdiction") +
  scale_fill_manual(values = jurisd_cols) -> all_jurisd_plot

# vis independently
jurisd_plot_list <- list()
for(i in 1:length(jurisd_cols)){
  jurisd_plot_list[[i]] <- mt_covariates %>% 
    filter(jurisdiction == jurisd_list[i]) %>% 
    ggplot() +
      geom_sf(data = grid_geometry) + 
      geom_sf(color = "black", fill = jurisd_cols[i]) +
      labs(title = jurisd_list[i], fill = "Jurisdiction")
}


```

::: {.panel-tabset}

## ALL
```{r}
all_jurisd_plot
```

## MFWP
```{r}
jurisd_plot_list[[1]]
```

## BLM
```{r}
jurisd_plot_list[[2]]
```

## USFS
```{r}
jurisd_plot_list[[3]]
```

## Res
```{r}
jurisd_plot_list[[4]]
```

## USFWS
```{r}
jurisd_plot_list[[5]]
```

## NPS
```{r}
jurisd_plot_list[[6]]
```

## DNRC
```{r}
jurisd_plot_list[[7]]
```
:::