---
title: "Model"
---


# Model Description 
## Basic model structure 

We consider a basic dynamic model with a Markovian structure, in which the state of each year is dependent on the state of the previous year. Transition probabilities (the probability of a site going from one state to another, or remaining in the same state the following year) are determined as functions of colonization and survival rates.

We start by determining the initial state for each site $i$, which follows a multinomial distribution: 

$$
z_{i,1} \sim Categorical(\Omega_i)
$$

where $\Omega_i$ is the state vector, with the probabilities of each site $i$ being in one of the states ($1,2,3$) on the first year ($t=1$), given by:

$$
\Omega_i = [\phi_1 \quad \phi_2 \quad \phi_3]
$$
The probability of a site being empty or unoccupied (state $1$) the first year is given by $\phi_1$, the probability of site $i$ having a few bats or many bats the first year is given by $\phi_2$ and $\phi_3$ respectively, where the subscript indicates the state.
Since the probabilities have to add up to 1, we can write the state vector probabilities in terms of one another, we reparameterize to: 

$$
\Omega_i = [1-\psi \quad \psi(1-r) \quad \psi r]_i
$$
where $\psi$ is the probability of a site being occupied and $r$ is the probability of an occupied site having *many bats*, thus the probability that a site is occupied with a *few bats* ($\psi(1-r)$) is equivalent to the probability that a sites is occupied ($\psi$) AND it is **not** occupied by many bats ($1-r$).


The state of each site $i$ in the following years ($t = 2 \dots T$) is given by: 

$$
z_{i,t}|z_{i,t-1} \sim Categorical(\Phi_{z{(t-1)}, z{(t)}, i, t})
$$
where the transition matrix determines the probabilities of a site going from one state to another, or remaining in the same state, depending on the state it was in on the previous year: 

$$
\Phi_{z{(t-1)}, z{(t)}, i,t} =  \begin{bmatrix}
                                \pi_{11} & \pi_{12} & \pi_{13} \\
                                \pi_{21} & \pi_{22} & \pi_{23} \\
                                \pi_{31} & \pi_{32} & \pi_{33}
                                \end{bmatrix}_{i,t}
$$
we can read $\pi_{n,m,i,t}$ as the probability that site $i$ transitions from state $n$ in year $t-1$ to state $m$ in year $t$. We reparameterize this transition matrix in terms of colonization ($\gamma$) and persistence ($\phi$), plus growth $G$ or decline $D$ when moving between the states of *few* and *many bats*. 

$$
\Phi_{z{(t-1)}, z{(t)}} =  \begin{bmatrix}
                                1-\gamma & \gamma & 0 \\
                                1-\phi_1 & \phi_1(1-G) &  \phi_1G\\
                                1-\phi_2 & \phi_2D & \phi_2(1 - D)
                                \end{bmatrix}
$$


Both the initial state vector $\Omega_i$ and the transition matrix $\Phi$ can be reparameterized in order to have these probabilities in terms of environmental covariates, which can then be modified by different management actions.

## Including covariates

Initially, I am only using covariates that NABAt used for their report, where the data release is found [here](https://www.sciencebase.gov/catalog/item/620e6f3bd34e6c7e83baa603), and the report [here](https://ecos.fws.gov/ServCat/Reference/Profile/144755). Descriptions on how these covariates were obtained and aggregated at the cell level are found in the report. Briefly, 

-   Physiographic diversity on page 8 of the report - it's a measure of landscape complexity: ruggedness [source](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0143619)

-   Ecoregions could be very useful as they describe habitat features descriptions for ecoregions are [here](https://www.epa.gov/eco-research/level-iii-and-iv-ecoregions-continental-united-states) and the [paper](https://link.springer.com/article/10.1007/s00267-014-0364-1)
    -   in the report they mention these can be used to account for spatial autocorrelation seems like in their model they use these as the intercept

-   karst - grid cells that intersect karst polygons get a 1, source is this [paper](https://link.springer.com/article/10.1007/s10040-016-1519-3)  karst indicator was included to capture the effect of caves

-   riverlake variable is a 1 if the grid intersects rivers or shorelines

- For detection-level covariates they extracted the data from [here](https://daac.ornl.gov/cgi-bin/dsviewer.pl?ds_id=1852)
    - These depend on the specific night and where not provided in the data release 
    
    
Based on the MYLU ecological model presented in the report, I included the following covariates as predictors for the initial state occupancy:

With state vector,

$$
\Omega_i = [1-\psi \quad \psi(1-r) \quad \psi r]_i
$$

the probability of occupancy for site $i$, $\psi_i$ is set as: 

$$
\begin{align*}
logit(\psi_i) = \beta_0 + \beta_1 \cdot \text{Elevation} + \beta_2 \cdot \text{Elevation}^2 +
\beta_3 \cdot \text{Temp} + \beta_4 \cdot \text{Temp}^2 + \\
\beta_5 \cdot \text{Physiographic diversity} +
\beta_6 \cdot \text{Precipitation} + \\
\beta_7 \cdot \text{Percent Forest} + \beta_8 \cdot \text{Percent Wetlands}
\end{align*}
$$

What we think could influence whether there are only a few or many bats could be related to caves (karst), percent forest, and ruggedness (physiographic diversity)

$$
logit(r_i) = \beta_0 + \beta_1 \cdot \text{karst} + \beta_2 \cdot \text{Percent Forest} + 
                \beta_3 \cdot \text{Physiographic diversity}
$$
For both parameters, I included the ecoregion with the intercept, so we have region-specific intercepts

